
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: influxdb2-sm
  namespace: team4
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: influxdb2
      app.kubernetes.io/name: influxdb2
  namespaceSelector:
    matchNames:
      - team4
  endpoints:
    - port: http
      interval: 30s
      path: /metrics
