apiVersion: v1
kind: Service
metadata:
  name: prometheus-kafka-exporter
  namespace: team4
  labels:
    app.kubernetes.io/name: kafka-exporter
    strimzi.io/cluster: team4-kafka
spec:
  selector:
    app.kubernetes.io/name: kafka-exporter
    strimzi.io/cluster: team4-kafka
  ports:
    - name: prometheus
      port: 9308
      targetPort: 9308
