
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: team4
  labels:
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: prometheus-kafka-exporter
  namespaceSelector:
    matchNames:
      - team4
  endpoints:
    - port: metrics
      interval: 30s
      path: /metrics
