
apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: dual-role
  namespace: ${namespace}
  labels:
    strimzi.io/cluster: ${cluster}
spec:
  replicas: 1
  roles: [controller, broker]
  storage:
    type: ephemeral
